DROP TABLE IF EXISTS "limitation_triggers" CASCADE;
DROP TABLE IF EXISTS "limitation_options" CASCADE;
DROP TABLE IF EXISTS "limitation_questions" CASCADE;
DROP TABLE IF EXISTS "assessment_answers" CASCADE;
DROP TABLE IF EXISTS "assessment_questions" CASCADE;
DROP TABLE IF EXISTS "option_follow_up_prompts" CASCADE;
DROP TABLE IF EXISTS "option_doctrinal_sources" CASCADE;
DROP TABLE IF EXISTS "examination_options" CASCADE;
DROP TABLE IF EXISTS "examination_questions" CASCADE;
DROP TABLE IF EXISTS "doctrinal_sources" CASCADE;
DROP TABLE IF EXISTS "editorial_catalog_versions" CASCADE;
DROP TYPE IF EXISTS "editorial_status";
DROP TYPE IF EXISTS "objective_matter_classification";
DROP TYPE IF EXISTS "objective_matter_operator";
DROP TYPE IF EXISTS "follow_up_prompt_kind";
DROP TYPE IF EXISTS "rule_status";
CREATE TABLE "current_editorial_catalog" ("id" serial PRIMARY KEY NOT NULL, "schema_version" text NOT NULL, "locale" text NOT NULL UNIQUE, "title" text NOT NULL, "purpose" text NOT NULL, "global_notice" text NOT NULL);
CREATE TABLE "doctrinal_sources" ("id" serial PRIMARY KEY NOT NULL, "catalog_id" integer NOT NULL REFERENCES "current_editorial_catalog"("id") ON DELETE CASCADE, "code" text NOT NULL, "document" text NOT NULL, "locator" text NOT NULL, "authority_level" text NOT NULL, "official_url" text NOT NULL, CONSTRAINT "doctrinal_sources_catalog_code_unique" UNIQUE("catalog_id", "code"));
CREATE TABLE "examination_questions" ("id" serial PRIMARY KEY NOT NULL, "catalog_id" integer NOT NULL REFERENCES "current_editorial_catalog"("id") ON DELETE CASCADE, "code" text NOT NULL, "position" integer NOT NULL CHECK ("position" >= 0), "title" text NOT NULL, "prompt" text NOT NULL, "help_text" text NOT NULL, CONSTRAINT "examination_questions_catalog_code_unique" UNIQUE("catalog_id", "code"), CONSTRAINT "examination_questions_catalog_position_unique" UNIQUE("catalog_id", "position"));
CREATE TABLE "examination_options" ("id" serial PRIMARY KEY NOT NULL, "question_id" integer NOT NULL REFERENCES "examination_questions"("id") ON DELETE CASCADE, "code" text NOT NULL, "position" integer NOT NULL CHECK ("position" >= 0), "label" text NOT NULL, "response_kind" "response_kind" NOT NULL, "exclusive" boolean NOT NULL, "summary_text" text, CONSTRAINT "examination_options_question_code_unique" UNIQUE("question_id", "code"), CONSTRAINT "examination_options_question_position_unique" UNIQUE("question_id", "position"), CONSTRAINT "examination_options_shape_check" CHECK (("response_kind" = 'affirmation' AND "exclusive" = false AND "summary_text" IS NOT NULL) OR ("response_kind" = 'denial' AND "exclusive" = true AND "summary_text" IS NULL)));
CREATE TABLE "option_doctrinal_sources" ("option_id" integer NOT NULL REFERENCES "examination_options"("id") ON DELETE CASCADE, "doctrinal_source_id" integer NOT NULL REFERENCES "doctrinal_sources"("id") ON DELETE CASCADE, PRIMARY KEY("option_id", "doctrinal_source_id"));
CREATE INDEX "doctrinal_sources_catalog_idx" ON "doctrinal_sources" ("catalog_id");
